// <auto-generated />
using System;
using Formular1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formular1.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220316135900_Messe")]
    partial class Messe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Formular1.Shared.HotelZimmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Abreisetag")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Anreisedatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTeilnehmer")
                        .HasColumnType("int");

                    b.Property<string>("ZimmerForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Übernachtung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HotelZimmers");
                });

            modelBuilder.Entity("Formular1.Shared.Teilnehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Anrede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BgAnrede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BgEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mitBegleitung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teilnehmers");
                });

            modelBuilder.Entity("Formular1.Shared.TeilnehmerPVLive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnredeKollege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnzahlKollege")
                        .HasColumnType("int");

                    b.Property<string>("EmailKollege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTeilnehmer")
                        .HasColumnType("int");

                    b.Property<string>("Minderjährig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKollege")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeilnahmePVLive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amSamstag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amSonntag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mitKollegen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeilnehmerPVLives");
                });
#pragma warning restore 612, 618
        }
    }
}
